version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: helloscraper
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    volumes:
    - data.ms:/data.ms
    ports:
    - "7700:7700"      
      
volumes: 
  db:
  data.ms:
