# baseURL
@baseURL = http://localhost:3000

###
# Scrape weburl images
POST {{ baseURL }}/scraper
Content-Type: application/json

{
    "urls": [
        "https://yog9.github.io/SnapShot",
        "https://scrapeme.live/shop/"
    ]
}

###
# Get All Medias
GET {{ baseURL }}/scraper